apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhnmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhnmart
  template:
    metadata:
      labels:
        app: dhnmart
    spec:
      containers:
      - image: okteto.dev/dhnmart:latest
        name: dhnmart
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d108b522-d367-4144-9ebd-7ab7e817b008"
        - name: Vless_Path
          value: "/vl52555"
        - name: Vmess_UUID
          value: "d108b522-d367-4144-9ebd-7ab7e817b008"
        - name: Vmess_Path
          value: "/vm867986"
        - name: Share_Path
          value: "/v2link"
